### ISSUE TITLE
WIP Raid hardmode

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/progression-system#51]
The following is a suggestion and all details are up for discussion

There should be a way for players (raidleaders) to choose an alternative difficulty (heroic) for classic raids. Since the alternative difficulty can not be selected from the client's ususal menu without modications, we need an alternative way to activate it.

Features:
- Heroic raid is an own ID. One can do the normal and the heroic version in the same lockout period.
- NPC /gobject or another convenient way to activate heroic mode. Must be outside the raid map to be able to switch before entering
- Once in heroic mode, the players/pets/minions inside the raid are going to get debuffed (handled [here](https://github.com/55Honey/Acore_ZoneDebuff/tree/feature) , needs a check for heroic mode added). 
- In heroic mode, the loot is **replaced** by a (custom) currency dropped by each boss of the raid (the [lootmode-bitmask](https://www.azerothcore.org/wiki/loot_template#lootmode) from creature_loot_template might work well for this)
- There should an NPC in both Orgrimmar and Stormwind which sells rewards in return for the heroic currency
- A timestamp and the present players Low GUIDs should be stored in the DB for later display of records on the website. 1) When the heroic map is created, 2) on first combat, and 3) when a heroic boss dies.

**Comment by temperrr** [comment]
So you get loot from normal, loot from heroic, and extra loot from currency. That's a bit much?

**Comment by 55Honey** [comment]
We don't need to define loot details now. I think the main point is to have a blizzlike experience and the possibilty to take a challenge on top.

If we decide that this is too much loot, we could look into other options, e.g. only currency and gold loot in Classic heroic raids.

All just brainstorming at this point.
